Read from env variables for the default web bundle
tectonic-typesetting/tectonic pull request #1131
Opened 2023-12-15 12:19 UTC by bryango

This commit makes it easy to override the default web bundle through the environment variables (or in `build.rs`):

- `TECTONIC_WEB_BUNDLE_PREFIX`
- `TECTONIC_WEB_BUNDLE_LOCKED`

The PREFIX variable makes it easy for people to track a mirrored bundle, while the LOCKED variable ensures reproducible builds across all CLIs.

Currently, the default web bundle is hardcoded, as observed in #1002. This PR thus serves as a temporary solution for #1002. A related issue is the version mismatch between biber and the tectonic bundle #893, which we would like to address in nixpkgs https://github.com/NixOS/nixpkgs/pull/273740. This can be partially resolved by always pinning the compatible versions of biber and the tectonic bundle, which is made possible with this PR.

P.S. I am very new to rust, so if the code / interface is no good, please help me improve! And thank you for this wonderful package!

2023-12-16 18:34 UTC, rm-dr commented
This is somewhat related to #1121, which completely overhauls Tectonic's bundles (and thus conflicts with the changes here)

Notably, #1121 adds a new bundle format, and setting a variable for just the url prefix won't work. It may be a better idea (even without extra bundles) to have the variable contain the whole URL.

Also, I don't think I understand the difference between the LOCKED and PREFIX variables. Is there any reason to have two? I think one variable that overrides the default bundle url should be enough.


A few more notes about the issue in #1002:
 - Should this be a cli option or a env variable?
 - Why does `tectonic new` touch the network in the first place? I'd argue that the command should create a skeleton project completely offline (with the default url in `tectonic.toml`), which can be changed later by the user. This is clearer and doesn't need any extra config options.

2023-12-17 02:29 UTC, bryango commented
Hi @rm-dr! Thank you for the comment!

> This is somewhat related to #1121, which completely overhauls Tectonic's bundles (and thus conflicts with the changes here)

Wow amazing! I didn't know this before! This is a huge change though. Are you aware of https://github.com/tectonic-typesetting/tectonic/discussions/1122? I think being a member would probably make it easier to land these changes.

> Notably, #1121 adds a new bundle format, and setting a variable for just the url prefix won't work. It may be a better idea (even without extra bundles) to have the variable contain the whole URL.
> 
> Also, I don't think I understand the difference between the LOCKED and PREFIX variables. Is there any reason to have two? I think one variable that overrides the default bundle url should be enough.

Currently, the bundle url depends on the `format_version`:
https://github.com/tectonic-typesetting/tectonic/blob/c64e5243467fe94a1a6abe95cf8163ac2b3faacd/crates/bundles/src/lib.rs#L108-L123
So the PREFIX variant only modifies the prefix, in this case `https://relay.fullyjustified.net`, and keeps the version suffix `default_bundle_v{format_version}.tar`. If this is going away in the future, then only the LOCKED variant is needed. What do you think? Should I simply remove the PREFIX variant?
 
> Should this be a cli option or a env variable?

They are different! Let me clarify:
- the env variable provides a **build time** override for distro packagers, such that the tectonic bundle they distributed will match the biber version they distributed. This is related to #893.
- the `--web-bundle` option is for **runtime** override by the end user. This relates to #1002.

I think for the runtime override, we should only provide the CLI option, because env variables are more implicit and thus reduce reproducibility. For build time, however, I think env variables are the only way to pass around the customized build constants, so I have to use it.

> Why does `tectonic new` touch the network in the first place? I'd argue that the command should create a skeleton project completely offline (with the default url in `tectonic.toml`), which can be changed later by the user. This is clearer and doesn't need any extra config options.

AFAIK, `tectonic -X new` and `init`:
- takes a generic web bundle link `https://relay.fullyjustified.net/default_bundle_v33.tar`,
- redirects it to a _version-locked_ one, such like `https://data1.fullyjustified.net/tlextras-2022.0r0.tar`,
- and finally pins it down in the `Tectonic.toml` file.

I think this behavior is nice as it maximizes reproducibility. There are some suggestions in issues to put the locked url `...tlextras-2022.0r0.tar` in a dedicated `Tectonic.lock` file. When and if that happens, `tectonic -X new` and `init` can be completely offline, as it only needs to write the unlocked link `...default_bundle_v33.tar`.

2023-12-18 09:34 UTC, doronbehar commented
I really like the idea of having an environment variable for this, but I also don't understand why we need 2 environment variables, and not only 1.

Besides that, I also support having this environment variable read in runtime and not build time, as this would also help users to test different bundles in a different way, I think there is no advantage in terms of reproducibility between reading this environment variable in runtime vs build time; since Tectonic from different distributions may have different environments anywhere.

I also think it'd be fair for Tectonic to not guarantee reproducibility in case it reads a dedicated environment variable, and there's a conflict with the URL in the `Tectonic.toml` file. In such a case I think it'd be best to simply print a big warning, saying that we used the URL from the environment variable and not the the URL from `Tectonic.toml` file.

2023-12-18 10:34 UTC, bryango commented
Hi @doronbehar! Thank you very much for the comment!

1. I am absolutely okay with a single env variable such as `TECTONIC_WEB_BUNDLE_URL`. As explained above, the `PREFIX` variant is only introduced for backward compatibility and ease of mirroring. If we decide that it is confusing, I can easily remove it!

2. When it comes to runtime, I would still prefer explicit flags such as `--web-bundle`, which can be overridden by a second `--web-bundle`. (Is this the current behavior? I would have to try it out...)

> I think there is no advantage in terms of reproducibility between reading this environment variable in runtime vs build time; since Tectonic from different distributions may have different environments anywhere.

Yes, this is true in reality, but ideally, I would like Tectonic to _not_ read _any_ environment variables at all (at runtime), by design. It's like the new flake-y nix no longer reads the `NIXPKGS_*` env variables; sure, it makes things a bit more inconvenient, but I like the purity in the UI.

I know @pkgw is probably busy, but since this is now more than a bugfix and related to the UI design, I would very much like to hear your opinion, and I can fix the code accordingly!

2023-12-18 11:15 UTC, doronbehar commented
> 2\. When it comes to runtime, I would still prefer explicit flags such as `--web-bundle`, which can be overridden by a second `--web-bundle`. This is not yet the current behavior, and I can look into fixing it.

I did noticed that the 2nd commit of this PR as of currently is referring to this? But not completely? Maybe it'd be easier for upstream to digest this change only in a PR of its own.

2023-12-18 17:40 UTC, rm-dr commented
> They are different! Let me clarify:

Ah, I see. We really do need a compile-time option for this.
The two-link config is a bit messy, but I see why it's necessary...

and I don't think I know a better way to do this, if we want easy bundle updates through a "default" redirect.

2023-12-19 05:20 UTC, bryango commented
Following the suggestion of @doronbehar I have moved the CLI changes to a separate PR #1132. These two PRs are both related to the web bundle interface, but they are technically independent, so it would be easier to review this way.

2024-02-04 19:34 UTC, pkgw commented
I've merged #1132, so that this PR becomes a lot smaller.

It does seem reasonable to me to have the default bundle URL be build-time configurable, for specialized applications.

My only comment upon first glance is one of the evergreen ones: these changes should be documented somewhere!

2024-02-05 01:52 UTC, bryango commented
> My only comment upon first glance is one of the evergreen ones: these changes should come with corresponding documentation somewhere!

Yes indeed! But since #1132 has been merged, this one is no longer a blocking issue for me :laughing: I will try to document it some time!

2025-03-01 07:53 UTC, bryango commented
The top level bundle override `tectonic --web-bundle -X ...` broke after the bundle work:
- #1218

... so we need this again for downstream reproducible packaging / distribution of tectonic. I have added the relevant documentation in the tectonic book. 

It would be great if this patch is considered before the next release; that would make downstream packaging much easier :laughing: Thank you! @rm-dr @CraftSpider @pkgw

2025-06-18 17:23 UTC, CraftSpider commented
I'll have to take some time to familiarize myself with our bundle code, but I'll try to take a look at this.

2025-07-24 22:18 UTC, CraftSpider requested changes

2025-07-24 22:18 UTC, CraftSpider commented on docs/src/howto/build-tectonic/bundle-default-config.md
> +where `$_vFORMAT_VERSION` is a suffix from an internal variable, used to distinguish different versions
```suggestion
where `$FORMAT_VERSION` is a suffix from an internal variable, used to distinguish different versions
```

2025-07-24 22:18 UTC, CraftSpider commented on crates/bundles/build.rs
> +    println!("cargo::rustc-env={LOCKED_VAR_NAME}={bundle_locked}");
I'd remove this whole build script, and just do an `unwrap_or(TECTONIC_BUNDLE_PREFIX_DEFAULT)` in `lib.rs`. The environment variables will be passed through to `rustc` by default.

2025-07-25 02:48 UTC, bryango commented on crates/bundles/build.rs
> +    println!("cargo::rustc-env={LOCKED_VAR_NAME}={bundle_locked}");
Good idea! Let me try!

2025-07-27 08:28 UTC, bryango commented
> I'd remove this whole build script, and just do an `unwrap_or(TECTONIC_BUNDLE_PREFIX_DEFAULT)` in `lib.rs`. The environment variables will be passed through to `rustc` by default.

This is now done! I added a commit that moves the changes to `lib.rs`. Note that:
- Now I remember the reason that I chose to put the variables in `build.rs` instead of `lib.rs` is for discoverability: back then I have not yet written docs for these new compile time env vars, so I want it to be in a more visible place. However, docs are now included in the PR, so I guess it's easier for them to reside in `lib.rs`
- In the final commit I added some tests for these environment variables. Since we are testing compile time behaviors I created a mini sub crate under /tests/bundle_env_overrides_test and it's compiled by tests/bundle_env_overrides.rs to verify these behaviors.
	- The test turns out to be a bit too complicated than I would like it to be, so feel free to drop it if it feels unnecessarily complex!

2025-07-28 17:22 UTC, merged

2025-07-28 17:23 UTC, CraftSpider commented
Thank you for keeping up on this after a whole year and a half of waiting - hopefully a 0.16 release can be cut soon.

2025-07-29 01:51 UTC, bryango commented
I should thank you for taking care of the project! Once I experienced Tectonic, I don't want to go back to texlive anymore, so I am just trying my best to help it live on 😆